{% set name = "r-catboost" %}
{% set version = "0.10.4" %}
{% set sha256 = "1419333fdfdf9a89397016a8c36f627c659bada1ccb89e39d68f895a732ba536" %}  # [unix]
{% set sha256 = "9b58c4e821081940ddf73c0ab68d341b68a277673581c0ed319753cbaadd01ef" %}  # [win]
{% set sha256 = "0cba6fbf4483440c39b18c3c9e164c34e5954543c8416020a36fbb80101fd3bd" %}  # [osx]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Linux-{{ version }}.tgz  # [unix]
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Windows-{{ version }}.tgz  # [win]
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Darwin-{{ version }}.tgz  # [osx]
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - r-base
    - r-devtools
  run:
    - r-base

test:
 commands:
    - $R -e "library('catboost')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""  # [win].

about:
  home: https://github.com/catboost/catboost
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.'
  doc_url: https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - curious-odd-man
    - dbast
