{% set name = "r-catboost" %}
{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Linux-{{ version }}.tgz  # [linux]
  sha256: 532068036c2bcc7bd3dfb8ca84f81bd37def5ccd1a86f5a1204f5bf8682684ea  # [linux]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Windows-{{ version }}.tgz  # [win]
  sha256: ac4093f80293f3e01ab30a24c13f4751628396213182f2c7d3eda586a0c60619  # [win]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Darwin-{{ version }}.tgz  # [osx]
  sha256: 3de0abaebdb830e09623047e10b3c0df8b74b2579675c51b25b6f2a1af7a3d72  # [osx]

build:
  number: 2

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-jsonlite
  run:
    - r-base
    - r-jsonlite

test:
  requires:
    - r-caret
    - r-testthat
    - r-tibble
  source_files:
    - tests/testthat/
  commands:
    - $R -e "library('catboost')"                                                                        # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_model.R')"                     # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""                                                                        # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_model.R')\""                     # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')\""  # [win]

about:
  home: https://github.com/catboost/catboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.
  doc_url: https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

extra:
  recipe-maintainers:
    - conda-forge/r
    - curious-odd-man
