{% set name = "r-catboost" %}
{% set version = "1.2.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-linux-x86_64-{{ version }}.tgz  # [linux and x86_64]
  sha256: fe02d9f5921ed74ddb900c80d9ae917453cd5aebd9bc2476c6088cc5c869836a  # [linux and x86_64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-linux-aarch64-{{ version }}.tgz  # [linux and aarch64]
  sha256: 22f3e2879821197482a31853ae5fabf916968db1283a35182110a411de6b5b49  # [linux and aarch64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-windows-x86_64-{{ version }}.tgz  # [win and x86_64]
  sha256: 97c3632044e0496f06e513b9610ff8226be51ccfcbe8e24ecf94b7e4ebf667d4  # [win and x86_64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-darwin-universal2-{{ version }}.tgz  # [osx]
  sha256: 26f14ac491ad1138663dde64bc3b270212d1804eb1c33eee3fdead26487d8bc1  # [osx]

build:
  number: 1
  # TODO: support Linux on ppc64le: https://github.com/catboost/catboost/issues/1755
  skip: true  # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-jsonlite
  run:
    - r-base
    - r-jsonlite

test:
  requires:
    - r-caret
    - r-testthat
    - r-tibble
  source_files:
    - tests/testthat/
  commands:
    - $R -e "library('catboost')"                                                                        # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_model.R')"                     # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""                                                                        # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_model.R')\""                     # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')\""  # [win]

about:
  home: https://github.com/catboost/catboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.
  doc_url: https://catboost.ai/docs/

extra:
  recipe-maintainers:
    - andrey-khropov
    - conda-forge/r
    - curious-odd-man
