{% set name = "r-catboost" %}
{% set version = "1.2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-linux-x86_64-{{ version }}.tgz  # [linux and x86_64]
  sha256: c56beafb3a485326b0f51ee4b80301b3a056aa76b2b6e6e10f5f606227f908dc  # [linux and x86_64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-linux-aarch64-{{ version }}.tgz  # [linux and aarch64]
  sha256: 6067cdc5adf3cd3be98a08d6bb9f584b4e4cd1a18bb9bf255c38aa196ce501eb  # [linux and aarch64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-windows-x86_64-{{ version }}.tgz  # [win and x86_64]
  sha256: 9e74db69752baeda239ba48e8ae4b8f08a4c9a15ec344aa0eb0c7ee5f528ed7f  # [win and x86_64]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-darwin-universal2-{{ version }}.tgz  # [osx]
  sha256: 4bf77a01281e90c83b2cb2ad87f8f376cb77bf66195e02a247c11051afa6f382  # [osx]

build:
  number: 0
  # TODO: support Linux on ppc64le: https://github.com/catboost/catboost/issues/1755
  skip: true  # [ppc64le]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-jsonlite
  run:
    - r-base
    - r-jsonlite

test:
  requires:
    - r-caret
    - r-testthat
    - r-tibble
  source_files:
    - tests/testthat/
  commands:
    - $R -e "library('catboost')"                                                                        # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_model.R')"                     # [not win]
    - $R -e "library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""                                                                        # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_model.R')\""                     # [win]
    - "\"%R%\" -e \"library('catboost');testthat::test_file('tests/testthat/test_on_trimmed_adult_dataset.R')\""  # [win]

about:
  home: https://github.com/catboost/catboost
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.
  doc_url: https://catboost.ai/docs/

extra:
  recipe-maintainers:
    - andrey-khropov
    - conda-forge/r
    - curious-odd-man
