{% set name = "r-catboost" %}
{% set version = "0.15" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Linux-{{ version }}.tgz  # [linux]
  sha256: abfdf346f1d448f0fd44602dca5b799eebef1efa775fee64f604f28af0b3f30f  # [linux]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Windows-{{ version }}.tgz  # [win]
  sha256: d07103be64e1fc79fd43d55a5eee522847dd4fbb3fcaf9f7dc6096b411a018cd  # [win]

  url: https://github.com/catboost/catboost/releases/download/v{{ version }}/catboost-R-Darwin-{{ version }}.tgz  # [osx]
  sha256: bc986bf1edd3e495618fd2b3e5375121009757d932908f000607a48f291cccd4  # [osx]

build:
  number: 0

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-jsonlite

  run:
    - r-base
    - r-jsonlite

test:
 commands:
    - $R -e "library('catboost')"  # [not win]
    - "\"%R%\" -e \"library('catboost')\""  # [win].

about:
  home: https://github.com/catboost/catboost
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'CatBoost is a machine learning algorithm that uses gradient boosting on decision trees. It is available as an open source library.'
  doc_url: https://tech.yandex.com/catboost/doc/dg/concepts/about-docpage/

extra:
  recipe-maintainers:
    - conda-forge/r
    - curious-odd-man
