# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kOHqdMaOeYXPtSBecQInSkne0YWsjw6xmiC9dXLT1ONmWkbiQ0+bkjBVwhrZ8cZAr9JzwDFRuqBctM3M8hEKbwVKDQeGdc70/ZFfeV2ymJcKxZaJ50p3UZD/jOTOhH1LOQ1/LAOnA8hlu1o6GirtZxwE66v1YN7+9TrDSMR5Cp6oyZDf4O3Kx2bDZoxUW/XH4NE/Fbb0ilX3xnQC/hiIvIGMya6DdLAmgpKEDzL6+xaab3wT8ALI90wcVCg5XbHR5HlvNNRDNp5W8MuyUpNMjhT8TliIzdXc64V6MCz1kQ9ZNCwMQ6Gy14X56yepbUc0/SzaYsvAnXrqV2NbplCcRvG18bPw/narAAvFsRQc0jToU89sYW2oub5K4cqlpzOSPgwQ8xevXYc72BPAvx+jvQMr9qffIwm87GNKwilZ+wvRjlwZMK4V+4PYfNEMdN+tvb9T3DX9zeLPObeYwFa9Oz9+T0S01Lh/LDA1Kibppaa5Vogh3vUpWW+HouAxLtS8q2p/2MnPmG/ou8ai7ABltOhPkuHtN5AZCXPvjKhdBdhsNHn2IGCWF+JE4JAJq9kqDKyxQ7LCugyFS7kGtSIXT/T4SBh6rnWbTqIjL/4s5oAjzgD5neGdPbEYxyzIjxGi893oFsyw6w2W+Kd6qkTnnmPFll8T7e2YJEckZIWq4uA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
